name: Deploy Infrastructure
on:
  push:
    branches:
      - "master"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write # AWS OIDC
  contents: read # Checkout

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_NUMBER }}:role/github-oidc-role
          aws-region: us-east-1
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Generate Terraform Plan
        uses: dflook/terraform-plan@v1

      # - name: Init Terraform
      #   run: terraform init

      # This does not work as the TF State is not saved and loaded when planning.
      # TODO: Pull and push TF state from S3 and deploy automatically or create an API of some sort to manage it.
      
      # - name: Deploy Terraform Plan
      #   run: terraform apply -auto-approve
